
require(RobExtremes)
G0 <- GParetoFamily(shape=0.7,of.interest="quantile", p=0.99)
IC1 <- optIC(InfRobModel(G0,ContNeighborhood(rad=0.5)), risk=asMSE())
set.seed(20130527)
x <- r(G0)(2000)
res <- kStepEstimator(x, IC1)

G0 <- GParetoFamily(shape=0.7,of.interest="quantile", p=0.99)
IC0 <- optIC(G0, risk=asCov())
IC1 <- optIC(InfRobModel(G0,ContNeighborhood(rad=0.5)), risk=asMSE())
plot(IC1)
IC2 <- optIC(InfRobModel(G0,ContNeighborhood(rad=0.5)), risk=asBias())
plot(IC2)
IC3 <- radiusMinimaxIC(G0,ContNeighborhood(rad=0.5), risk=asMSE())
IC3
plot(IC3)
G0a <- GParetoFamily(shape=0.7,of.interest="expected shortfall", p=0.99)
IC0a <- optIC(G0a, risk=asCov())
IC1a <- optIC(InfRobModel(G0a,ContNeighborhood(rad=0.5)), risk=asMSE())
plot(IC1a)
IC2a <- optIC(InfRobModel(G0a,ContNeighborhood(rad=0.5)), risk=asBias())
plot(IC2a)
IC3a <- radiusMinimaxIC(G0a,ContNeighborhood(rad=0.5), risk=asMSE())
IC3a
plot(IC3a)
set.seed(20130527)
x <- r(G0)(200)
res <- kStepEstimator(x, IC1)
estimate(res)
confint(res,level=.95)
q(distribution(G0))(.99)
set.seed(20130527)
x <- r(G0)(20000)
res <- kStepEstimator(x, IC1)
estimate(res)
confint(res,level=.95)
res00 <- MLEstimator(x, G0)
res0 <- kStepEstimator(x, IC0,steps=20)
estimate(res0)
confint(res0,level=.95)

G0 <- GEVFamily(shape=0.7,of.interest="quantile", p=0.99)
IC0 <- optIC(G0, risk=asCov())
IC1 <- optIC(InfRobModel(G0,ContNeighborhood(rad=0.5)), risk=asMSE())
plot(IC1)
set.seed(20130527)
x <- r(G0)(1500)
res <- kStepEstimator(x, IC1)
estimate(res)
confint(res,level=.95)
q(distribution(G0))(.99)
res00 <- MLEstimator(x, G0)
res0 <- kStepEstimator(x, IC0,steps=20)
estimate(res00)
estimate(res0)
confint(res0,level=.95)
q(distribution(G0))(.99)

require(RobExtremes)
G0 <- WeibullFamily(shape=0.7,of.interest="quantile", p=0.99)
IC0 <- optIC(G0, risk=asCov())
IC1 <- optIC(InfRobModel(G0,ContNeighborhood(rad=0.5)), risk=asMSE())
plot(IC1)
set.seed(20130527)
x <- r(G0)(1500)
res <- kStepEstimator(x, IC1)
estimate(res)
confint(res,level=.95)
q(distribution(G0))(.99)
res00 <- MLEstimator(x, G0)
res0 <- kStepEstimator(x, IC0,steps=20)
estimate(res00)
estimate(res0)
confint(res0,level=.95)
q(distribution(G0))(.99)
