getShapeGrid <- function(gridsize=1000,centralvalue=0.7,
                         withPos=TRUE, cutoff.at.0=1e-4, fac = 2){

 gridsize <- gridsize/2
 xi.a <- (1:round(gridsize))/(gridsize+1)*10
 p.u <- .25/gridsize
 q0 <- qnorm(seq(from=0.5,to=1-p.u,length=gridsize%/%2))
 q <- sort(c(-q0,q0))
 xi.g <- centralvalue + q*fac
 if(withPos){
    xi.g <- unique(pmax(xi.g,0))
    l.xi.g <- length(xi.g)
    if(l.xi.g<gridsize){
       n.d <- (gridsize-l.xi.g)%/%8
       n.u <- 7*n.d + (gridsize-l.xi.g)%%8
       xi.n <- (1:n.d)/(n.d+1)*min(xi.g[xi.g>1e-9])
       xi.g <- sort(unique(c(0,xi.n,xi.g[xi.g>1e-9])))
       if(n.u>0){
          p.u2 <- 1-p.u + p.u*(1:n.u)/(n.u+1)
          xi.u <- centralvalue + fac * qnorm(p.u2)
          xi.g <- c(xi.g,xi.u)
       }
    }
 }
 xi.g <- sort(xi.g[(abs(xi.g)>cutoff.at.0)])
 l.xi.g <- length(xi.g)
 n.d <- (gridsize-l.xi.g)%/%8
 n.u <- 7*n.d + (gridsize-l.xi.g)%%8

 if(n.u>0){
    p.u <- pnorm((xi.g[l.xi.g]-centralvalue)/fac, lower=FALSE)
    p.u2 <- 1-p.u + p.u*(1:n.u)/(n.u+1)
    xi.u <- centralvalue + fac * qnorm(p.u2)
    xi.g <- c(xi.g,xi.u)
 }

 if(n.d > 0 && !withPos){
    m.g.p <- min(pmax(xi.g,0))
    m.g.m <- min(pmax(-xi.g,0))
    n2.m <- n.d%/%2
    n2.p <- n2.m + n.d%%2
    xi.n.p <- cutoff.at.0+ (0:(n2.p-1))/n2.p*(m.g.p-cutoff.at.0)
    xi.g <- c(xi.g, xi.n.p)
    if(n2.m>0){
       xi.n.m <- cutoff.at.0- (1:n2.m)/(n2.m+1)*(m.g.m-cutoff.at.0)
       xi.g <- c(xi.g, xi.n.m)
    }
 }
 if(n.d > 0  && withPos){
    m.g <- min(xi.g)
    n2 <- n.d
    xi.n <- cutoff.at.0+ (0:(n2-1))/n2*(m.g-cutoff.at.0)
    xi.g <- c(xi.n, xi.g)
 }
 xi.g <- sort(unique(c(xi.g,xi.a)))
 return(xi.g)
}

getSnGrid <- function(xiGrid = getShapeGrid(), PFam=GParetoFamily(), low=0,
                      upp=1.01, accuracy = 10000, withSmooth = TRUE,
                      withPrint = FALSE){
   call <- match.call()
   itSn <- 0
   getSn <- function(xi){
               itSn <<- itSn + 1
               if(withPrint) cat("Evaluation Nr.", itSn," at xi = ",xi,"\n")
               distr <- PFam@modifyParam(theta=c("scale"=1,"shape"=xi))
               return(Sn(x=distr, accuracy = accuracy, low=low, upp = upp))
               }
   SnGrid <- sapply(xiGrid,getSn)
   iNA <- is.na(SnGrid)
   SnGrid <- SnGrid[!iNA]
   xiGrid <- xiGrid[!iNA]
   if(withSmooth)
      SnGrid <- smooth.spline(xiGrid,SnGrid)$y
   fct0 <- splinefun(x=xiGrid,y=SnGrid)
   xm <- xiGrid[1]
   ym <- SnGrid[1]
   dym <- (SnGrid[2]-SnGrid[1])/(xiGrid[2]-xiGrid[1])

   xM <- (rev(xiGrid))[1]
   yM <- (rev(SnGrid))[1]
   dyM <- ((rev(SnGrid))[2]-(rev(SnGrid))[1])/((rev(xiGrid))[2]-(rev(xiGrid))[1])
   fct <- function(x){
          y0 <- fct0(x)
          y1 <- y0
          y1[x<xm] <- ym+dym*(x[x<xm]-xm)
          y1[x>xM] <- yM+dyM*(x[x>xM]-xM)
          if(any(is.na(y0)))
             warning("There have been xi-values out of range of the interpolation grid.")
          return(y1)
   }
   return(list(grid = cbind(xi=xiGrid,Sn=SnGrid),
               fct = fct, call = call))
}

.saveInterpGrid <- function(xiGrid = getShapeGrid(), PFam = GParetoFamily(),
                        sysRdaFolder, getFun = getSnGrid,
                        ..., nameInSysdata = ".SnGrids",
                        withSmooth = TRUE, withPrint = TRUE,
                        Y = NULL, elseFun = NULL){
  if(missing(sysRdaFolder)) stop("You must specify argument 'sysRdaFolder'.")

  newEnv <- new.env()
  sysdataFile <- file.path(sysRdaFolder,"sysdata.rda")
  cat("sysdataFile = ", sysdataFile, "\n")

  if(file.exists(sysdataFile)){
     load(file=sysdataFile,envir=newEnv)
     whatIsThereAlready <- ls(envir=newEnv, all.names=TRUE)
  }else whatIsThereAlready <- character(0)

  cat("whatIsThereAlready = ", head(whatIsThereAlready), "\n")

  if(exists(nameInSysdata,envir=newEnv)){
    InterpGrids <- get(nameInSysdata, envir=newEnv)
    namesInterpGrids <- names(InterpGrids)
    cat(gettext("Names of existing grids:\n"))
    cat(paste("   ", namesInterpGrids , "\n"))

    if(name(PFam)%in% namesInterpGrids){
       cat(gettext("There already is a grid for family "), name(PFam),".\n",sep="")
       if(!is.null(InterpGrids[[name(PFam)]]$call)){
           cat(gettextf("It was generated by\n"),sep="")
           print(InterpGrids[[name(PFam)]]$call)
       }
       cat("\n",
           gettext("Do you really want to overwrite it (yes=1/no else)?"),"\n",
           sep="")
       ans <- try(scan(what=integer(1)), silent = TRUE)
       if(is(ans,"try-error")) ans <- 0
       if(ans==1){
          if(is.null(Y)) {
              InterpGrids[[name(PFam)]] <- getFun(xiGrid = xiGrid, PFam = PFam,
                         ..., withSmooth = withSmooth, withPrint = withPrint)
          }else{ if(!is.null(elseFun)){
                   InterpGrids[[name(PFam)]] <- elseFun(xiGrid, Y,
                                                      withSmooth = withSmooth)
                 }else return(NULL)
          }
                     
          l.ng <- -1
          cat(gettext("SnGrid successfully produced.\n"))
       }else l.ng <- -2
    }else l.ng <- length(InterpGrids)+1
  }else{
    l.ng <- 1
    InterpGrids <- vector("list",1)
    whatIsThereAlready <- c(whatIsThereAlready,nameInSysdata)
  }

  if(l.ng>0){
     if(is.null(Y)) {
           InterpGrids[[l.ng]] <- getFun(xiGrid = xiGrid, PFam = PFam,
                         ..., withSmooth = withSmooth, withPrint = withPrint)
     }else{ if(!is.null(elseFun)){
               InterpGrids[[l.ng]] <- elseFun(xiGrid, Y, withSmooth = withSmooth)
            }else return(NULL)
     }
     cat(gettext("Grid successfully produced.\n"))
     names(InterpGrids)[l.ng] <- name(PFam)
  }

  if(l.ng> -2){
     assign(nameInSysdata, InterpGrids, envir=newEnv)
     save(list=whatIsThereAlready, file=sysdataFile, envir=newEnv)
     tools::resaveRdaFiles(sysRdaFolder)
     cat(gettextf("%s successfully written to sysdata.rda file.\n",
            nameInSysdata))
  }
  rm(list=whatIsThereAlready,envir=newEnv)
  gc()
  return(invisible(NULL))
}

setMethod("Sn", signature(x = "GPareto"),
    function(x, ...){
           if(abs(scale(x)-1)< 1e-12){
#              sng <- .SnGrids
              sng <- getFromNamespace(".SnGrids", ns = "RobExtremes")
              snf <- sng[["Generalized Pareto Family"]][["fct"]]
              ret <- snf(shape(x))
           }else ret <- scale(x)*Sn(x=x/scale(x))
           return(ret)
    })


